name: Action Workflow

on: [push]

jobs:
    run-github-actions:
        runs-on: ubuntu-latest
        steps:
          - name: List Files Before
            run: |
              pwd
              ls -a
          - name: Checkout
            uses: actions/checkout@v1

          - name: List Files After checkout
            run: |
              pwd
              ls -a

          - name: Simple JS Action
            id: greets
            uses: actions/hello-world-javascript-action@v1 # Github账号名/仓库名@版本号
            with:
                who-to-greet: Bobby  #输入
          - name: log greeting time
            run: echo "${{ steps.greets.outputs.time }}" #输出，只想上一个“greets”的输出。

          - name: Evvironment Variables
            run: |
              echo $GITHUB_SHA
              echo $GITHUB_REPOSITORY
              echo $GITHUB_WORKSPACE
              echo "${{ github.token }}"

