name: Shell Commands

on: [push]  # push event

jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
          - name: print a string
            run: echo "Hello World Github Action."
          - name: multipy script
            run: |
              node -v
              npm -v
          - name: Python Command
            run: |
              import platform
              print(platform.processor())
            shell: python

    run-windows-command:
        runs-on: windows-latest
        steps:
          - name: Directory Powershell
            run: Get-Location
          - name: Directory Bash
            run: pwd
            shell: bash
    
